# Generated by Django 6.0.5 on 2026-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('travel_type', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City Tourism'), ('adventure', 'Adventure')], max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('attractions', models.TextField(blank=True)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
