# Generated by Django 6.0.5 on 2026-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-popularity_score', 'name']},
        ),
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_duration_max',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_duration_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_type',
            field=models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City Tourism'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('luxury', 'Luxury'), ('relaxation', 'Relaxation')], max_length=20),
        ),
    ]
