# Generated by Django 6.0.5 on 2026-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_destination_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
