# Generated by Django 6.0.5 on 2026-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_add_city_to_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(blank=True, choices=[('europe', 'Europe'), ('asia', 'Asia'), ('north_america', 'North America'), ('south_america', 'South America'), ('africa', 'Africa'), ('oceania', 'Australia & Oceania')], max_length=30),
        ),
    ]
