# Generated by Django 6.0.5 on 2026-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_add_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='travel_tips',
            field=models.TextField(blank=True, default=''),
        ),
    ]
