# Generated by Django 6.0.5 on 2026-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_add_travel_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cost_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
