# Generated by Django 6.0.5 on 2026-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description_mk',
            field=models.TextField(blank=True, default=''),
        ),
    ]
