# Generated by Django 6.0.5 on 2026-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_destination_description_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='name_mk',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
