# Generated by Django 6.0.5 on 2026-08-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_add_name_mk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_mk', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_mk', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Travel categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='best_season_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='destinations.season'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='destinations.travelcategory'),
        ),
    ]
