# Generated by Django 6.0.5 on 2026-08-30 11:38

from django.db import migrations

TRAVEL_TYPES = [
    ('beach', 'Beach'),
    ('mountain', 'Mountain'),
    ('city', 'City Tourism'),
    ('adventure', 'Adventure'),
    ('cultural', 'Cultural'),
    ('luxury', 'Luxury'),
    ('relaxation', 'Relaxation'),
]

SEASON_CHOICES = [
    ('spring', 'Spring'),
    ('summer', 'Summer'),
    ('autumn', 'Autumn'),
    ('winter', 'Winter'),
]


def seed_and_backfill(apps, schema_editor):
    TravelCategory = apps.get_model('destinations', 'TravelCategory')
    Season = apps.get_model('destinations', 'Season')
    Destination = apps.get_model('destinations', 'Destination')

    categories_by_slug = {}
    for order, (slug, name) in enumerate(TRAVEL_TYPES):
        categories_by_slug[slug] = TravelCategory.objects.create(
            slug=slug, name=name, order=order,
        )

    seasons_by_slug = {}
    for order, (slug, name) in enumerate(SEASON_CHOICES):
        seasons_by_slug[slug] = Season.objects.create(
            slug=slug, name=name, order=order,
        )

    for destination in Destination.objects.all():
        destination.travel_type_new = categories_by_slug.get(destination.travel_type)
        destination.best_season_new = seasons_by_slug.get(destination.best_season) if destination.best_season else None
        destination.save(update_fields=['travel_type_new', 'best_season_new'])


def noop_reverse(apps, schema_editor):
    # Irreversible by design (the old string columns are still present and
    # untouched at this point, so reversing forward-only backfill data is
    # not meaningful) - acceptable for this project, stated explicitly
    # rather than silently omitting reverse_code.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_season_travelcategory_destination_best_season_new_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_and_backfill, noop_reverse),
    ]
