# Generated by Django 6.0.5 on 2026-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_finalize_travel_type_season_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country_mk',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
