# Generated by Django 6.0.5 on 2026-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_add_country_mk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='booking_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='flight_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
