# Generated by Django 6.0.5 on 2026-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trip_duration_preference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_travel_type',
            field=models.CharField(blank=True, choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City Tourism'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('luxury', 'Luxury'), ('relaxation', 'Relaxation')], max_length=20),
        ),
    ]
