# Generated by Django 6.0.5 on 2026-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_add_region'),
        ('users', '0002_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visited_destinations',
            field=models.ManyToManyField(blank=True, related_name='visited_by', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist_destinations',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='destinations.destination'),
        ),
    ]
