# Generated by Django 6.0.5 on 2026-08-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
