# Generated by Django 6.0.5 on 2026-08-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_season_travelcategory_destination_best_season_new_and_more'),
        ('users', '0005_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_season_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destinations.season'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_travel_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destinations.travelcategory'),
        ),
    ]
