# Generated by Django 6.0.5 on 2026-08-30 11:39

from django.db import migrations


def backfill(apps, schema_editor):
    TravelCategory = apps.get_model('destinations', 'TravelCategory')
    Season = apps.get_model('destinations', 'Season')
    CustomUser = apps.get_model('users', 'CustomUser')

    categories_by_slug = {c.slug: c for c in TravelCategory.objects.all()}
    seasons_by_slug = {s.slug: s for s in Season.objects.all()}

    for user in CustomUser.objects.all():
        user.preferred_travel_type_new = categories_by_slug.get(user.preferred_travel_type) if user.preferred_travel_type else None
        user.preferred_season_new = seasons_by_slug.get(user.preferred_season) if user.preferred_season else None
        user.save(update_fields=['preferred_travel_type_new', 'preferred_season_new'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_preferred_season_new_and_more'),
        ('destinations', '0011_seed_categories_seasons'),
    ]

    operations = [
        migrations.RunPython(backfill, noop_reverse),
    ]
