# Generated by Django 6.0.5 on 2026-09-01 22:46

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    # Email verification is a new requirement, not retroactive - every
    # account that existed before this migration ran (self-registered,
    # admin-created, Google OAuth, or admin accounts) already had full
    # access, so none of them should suddenly be locked out of login.
    # Only accounts created *after* this point start at the model's
    # real default (False) and go through RegisterView's new email flow.
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_backfill_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
